### ISSUE TITLE
表示不知道怎么调用这个库

### ISSUE THREAD

**Issue by zhongwen1** [zhangliangming/HPLyrics#1]

**Comment by zhangliangming** [comment]
@zhongwen1 [https://github.com/zhangliangming/HPLyrics/blob/master/readme.md](url) 我在readme上面有说怎样引用这个依赖包的。还有我贴出了一个demo的地址：链接: [https://pan.baidu.com/s/1eA5pcs0pUnr9gXhosek9Bw](url) 密码: awcf  你可以看看这个HPLyrics-20180421.zip。里面有说调用的方法的。

**Comment by sing1** [comment]
demo链接都失效了

**Comment by zhangliangming** [comment]
看这个旧项目吧，里面有调用。https://github.com/zhangliangming/HappyPlayer5 @sing1 @zhongwen1
