### ISSUE TITLE
感谢zhangliangming大神提供这么棒的开源项目，我来试用一下、

### ISSUE THREAD

**Issue by liuhaifang** [zhangliangming/HPLyrics#10]
下载项目后app模块没有内容，运行不了呢，
文章里面提到的这个界面是怎么运行出来的呢
![image](https://user-images.githubusercontent.com/7792028/60090954-196cb300-9776-11e9-80ca-f0ffa52e5f86.png)

**Comment by liuhaifang** [comment]
https://www.jianshu.com/p/9e7111db7b41

**Comment by liuhaifang** [comment]
找到了，在说明文档后面有demo下载链接

**Comment by zhangliangming** [comment]
@liuhaifang github上面提供的代码，是方便用来引用的。它不是一个完整的项目。如果需要完整的项目，就到readme那里找一下，有一个调用的demo的链接。
