### ISSUE TITLE
Activity里面 setContentView(R.layout.activity_kge_cy);报错：Binary XML file line #143: Error inflating class com.zlm.hp.lyrics.widget.ManyLyricsView

### ISSUE THREAD

**Issue by liuhaifang** [zhangliangming/HPLyrics#11]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:gravity="center_horizontal"
    android:orientation="vertical">

    <RelativeLayout
        android:id="@+id/rlTop"
        android:layout_width="match_parent"
        android:layout_height="@dimen/top_height"
        android:background="@color/colorPrimary">

        <ImageView
            android:id="@+id/imageViewBack"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:layout_centerVertical="true"
            android:paddingLeft="20dp"
            android:paddingTop="17dp"
            android:paddingRight="20dp"
            android:paddingBottom="17dp"
            android:src="@drawable/back_arrow3x" />

        <TextView
            android:id="@+id/textViewTitle"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:text=""
            android:textColor="@color/white"
            android:textSize="20sp" />

    </RelativeLayout>

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="68dp"
        android:gravity="center"
        android:orientation="vertical">

        <ProgressBar
            android:id="@+id/progressBar"
            style="@style/Widget.AppCompat.ProgressBar.Horizontal"
            android:layout_width="280dp"
            android:layout_height="24dp"
            android:layout_centerInParent="true"
            android:max="100"
            android:progress="0"
            android:progressDrawable="@drawable/progress_bar_pingfen" />

        <ImageView
            android:id="@+id/imageViewAvatar"
            android:layout_width="43dp"
            android:layout_height="43dp"
            android:layout_centerVertical="true"
            android:layout_marginRight="-6dp"
            android:layout_toLeftOf="@id/progressBar"
            android:src="@drawable/avatar_default" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignBaseline="@id/progressBar"
            android:layout_centerVertical="true"
            android:layout_marginLeft="18dp"
            android:layout_toRightOf="@id/imageViewAvatar"
            android:text="0分"
            android:textColor="@color/white"
            android:textSize="12sp" />

    </RelativeLayout>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="76dp">

        <View
            android:layout_width="match_parent"
            android:layout_height="@dimen/line_height"
            android:background="@color/line" />

        <View
            android:layout_width="match_parent"
            android:layout_height="@dimen/line_height"
            android:layout_gravity="bottom"
            android:background="@color/line" />
    </FrameLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:paddingLeft="30dp"
        android:paddingRight="30dp">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:gravity="center_vertical"
            android:orientation="horizontal">

            <ImageView
                android:layout_width="8dp"
                android:layout_height="8dp"
                android:src="@drawable/luzhi3x" />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="5dp"
                android:text="录制 00:03/04:97"
                android:textColor="@color/gray3"
                android:textSize="12sp" />

        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="16dp"
            android:gravity="center"
            android:orientation="horizontal">

            <View
                android:layout_width="172dp"
                android:layout_height="@dimen/line_height"
                android:background="@color/line" />

            <Button
                android:layout_width="60dp"
                android:layout_height="22dp"
                android:background="@drawable/btn_normal_bg"
                android:text="关闭原唱"
                android:textColor="@color/white"
                android:textSize="12sp" />

        </LinearLayout>

        <com.zlm.hp.lyrics.widget.ManyLyricsView
            android:id="@+id/manyLyricsView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="30dp"
            android:layout_marginBottom="30dp"
            android:layout_weight="1"
            android:background="@color/white" />

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="70dp"
            android:orientation="horizontal">

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:gravity="center_horizontal|top"
                android:orientation="vertical">

                <ImageView
                    android:id="@+id/imageViewChongchang"
                    android:layout_width="30dp"
                    android:layout_height="30dp"
                    android:padding="3dp"
                    android:src="@drawable/image_chongchang" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="重唱"
                    android:textColor="@color/gray2"
                    android:textSize="14sp" />
            </LinearLayout>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:gravity="center_horizontal|top"
                android:orientation="vertical">

                <ImageView
                    android:id="@+id/imageViewShengjiangdiao"
                    android:layout_width="30dp"
                    android:layout_height="30dp"
                    android:padding="3dp"
                    android:src="@drawable/image_shengjiangdiao" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="升降调"
                    android:textColor="@color/gray2"
                    android:textSize="14sp" />
            </LinearLayout>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:gravity="center_horizontal|top"
                android:orientation="vertical">

                <ImageView
                    android:id="@+id/imageViewWancheng"
                    android:layout_width="30dp"
                    android:layout_height="30dp"
                    android:padding="3dp"
                    android:src="@drawable/image_wancheng" />

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="完成"
                    android:textColor="@color/gray2"
                    android:textSize="14sp" />
            </LinearLayout>
        </LinearLayout>

    </LinearLayout>

</LinearLayout>

**Comment by zhangliangming** [comment]
@liuhaifang 你这个，可能是我写的那个ManyLyricsView类，少写了几个构造方法导致的。
1.ManyLyricsView(Context context, @Nullable AttributeSet attrs, int defStyleAttr)
2.ManyLyricsView(Context context, @Nullable AttributeSet attrs, int defStyleAttr, int defStyleRes)
你补充一下，这两个构造方法看看
