### ISSUE TITLE
SDK29找不到ManyLricsView组件

### ISSUE THREAD

**Issue by foxluo9527** [zhangliangming/HPLyrics#14]
换了不同版本，只有1.7能找到组件,但是1.7版本没有lrcwy目录
![J2( GV%1V%1S}4G7VPU()}2](https://user-images.githubusercontent.com/59313578/76695960-5d1a9a80-66c0-11ea-8fce-0f4957d40a26.png)
![%16GLJ2K8F{7Y4@PDBZAECR](https://user-images.githubusercontent.com/59313578/76695973-96eba100-66c0-11ea-9df4-531a79deca3b.png)

**Comment by foxluo9527** [comment]
![_~ KV}K`WW V}ZQP7$MZ@2](https://user-images.githubusercontent.com/59313578/76696321-0e233400-66c5-11ea-9ffc-b9fc0f6f9041.png)

**Comment by foxluo9527** [comment]
![_~ KV}K`WW V}ZQP7$MZ@2](https://user-images.githubusercontent.com/59313578/76696323-25fab800-66c5-11ea-8d9f-4653e3eb2d79.png)

**Comment by zhangliangming** [comment]
@foxluo9527 我看了一下我的项目，是有的。你试下clean项目或者rebuild一下。
