### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by OkamiyGit** [zhangliangming/HPLyrics#3]
大佬，我在用歌词库的时候遇到了问题，求大佬帮忙分析下，542839122.万分感谢

**Comment by zhangliangming** [comment]
@OkamiyGit 你要先把问题列出来

**Comment by OkamiyGit** [comment]
我download你的源码，cv到项目，歌词变成竖向的了，还乱码？求帮忙。。看了一天也没个头绪。。。。

**Comment by zhangliangming** [comment]
@OkamiyGit 你留一下你的QQ号，我加你

**Comment by OkamiyGit** [comment]
542839122，感谢大佬

**Comment by OkamiyGit** [comment]
问题已解决，感谢大佬

**Comment by zhangliangming** [comment]
1.目前歌词格式默认是utf-8格式
2.注意引用的版本
1.x版本，只要是使用自定义view来实现。
2.x版本，主要是使用surfaceview来实现。
3.x版本，主要是使用TextureView来实现。
