### ISSUE TITLE
大佬请问一下这个是import的什么在哪里呀

### ISSUE THREAD

**Issue by QiShi17** [zhangliangming/HPLyrics#4]
![qq](https://user-images.githubusercontent.com/33092617/44180168-fb9bdf80-a0c8-11e8-9076-3d56215b1c75.png)

就是AbstractLrcView.java文件里的这个import com.zlm.libs.register.RegisterHelper;

**Comment by QiShi17** [comment]
不知道这个register.RegisterHelper放在哪里了~~是做什么用的~~

**Comment by zhangliangming** [comment]
@QiShi17 你留一下，你QQ，我加你

**Comment by QiShi17** [comment]
麻烦大佬了~昨天后来发现是gradle添加了一个依赖~~~非常感谢大佬！！是我没仔细看~~不好意思(#^.^#)

**Comment by zhangliangming** [comment]
@QiShi17 RegisterHelper是我为了之前的乐乐播放器加的一个注册码来的，你如果是通过依赖的方式引用我的歌词库（HPLyrics）的话，我建议你不要引用RegisterHelper这个依赖库，因为第二天，app会因为没有获取到注册码，会直接关闭的，不能使用。你可以通过以下方式来解决：
方法：把HPLyrics里面引用到RegisterHelper的代码删除
