### ISSUE TITLE
歌词显示竖的

### ISSUE THREAD

**Issue by chanzhao** [zhangliangming/HPLyrics#5]
大神，请问一下 歌词显示竖的怎么破啊？方便加下qq或者wx吗？

**Comment by zhangliangming** [comment]
关于这个歌词竖着显示的问题，主要是歌词view获取view的宽度失败了，导致的
1.请确保你的歌词view的布局，有没有调用：android:visibility="gone"，如果有，修改为android:visibility="invisible"
2.如果还不行，可以调用setTextMaxWidth设置歌词的最大宽度

**Comment by zhangliangming** [comment]
@chanzhao 你先试试，不行的话，留下你的Q号

**Comment by chanzhao** [comment]
qq:1350618780麻烦大神了。
