### ISSUE TITLE
关于代码

### ISSUE THREAD

**Issue by lixiaote** [zhangliangming/HPLyrics#7]
hello，哥们，你的 2.x和3.0以上版本代码没提交上来么，现在看到所有的歌词还是继承 View呀，另外，哥们可以把你的测试demo的代码也上传上来么，想研究下歌词这块，谢啦～

**Comment by zhangliangming** [comment]
@lixiaote 
1.关于2.x和3.x以上的版本，你可以到releases里面找到2.x和3.x对应的源码。
2.还有你说的测试Demo，其实在readme上面，有一个百度云的下载地址。
3.关于2.x和3.x版本存在的问题，我在readme上面都有说明。目前比较好的方案还是继承view。
